services:
  app:
    image: "${DOCKER_HUB_USERNAME}/RuthAPI:latest"
    container_name: RuthAPI
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/${RUTH_SERVER_USER}/RuthAPI/.env:/app/.env
    env_file:
      - .env
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    env_file:
      - .env
    ports:
      - '27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - '5432'