name: Deploy to RuthServer via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ruthapi:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ruthapi:latest

      - name: Create env file
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env
          echo "DOCKER_HUB_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" >> .env
          echo "RUTH_SERVER_HOST=${{ secrets.RUTH_SERVER_HOST }}" >> .env
          echo "RUTH_SERVER_USER=${{ secrets.RUTH_SERVER_USER }}" >> .env

      - name: Create backup zip file
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          ZIP_NAME="deploy_ruthapi_$TIMESTAMP.zip"
          zip -r $ZIP_NAME .env docker-compose.yml deploy.sh appspec.yml
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Deploy to RuthServer
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RUTH_SERVER_HOST }}
          username: ${{ secrets.RUTH_SERVER_USER }}
          key: ${{ secrets.RUTH_SERVER_SSH_KEY }}
          source: ".env,docker-compose.yml,deploy.sh,appspec.yml"
          target: "/home/${{ secrets.RUTH_SERVER_USER }}/RuthAPI"

      - name: Execute deploy script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.RUTH_SERVER_HOST }}
          username: ${{ secrets.RUTH_SERVER_USER }}
          key: ${{ secrets.RUTH_SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.RUTH_SERVER_USER }}/RuthAPI
            chmod +x deploy.sh
            ./deploy.sh